package org.example.planemuseumbackend.Entities;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "plane",
        uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Plane {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    int id;
    String manufacturer;
    @Column(unique = true, nullable = false)
    String name;
    String type;
    int yearOfManufacture;
    String countryOfOrigin;
    String description;
    String imageUrl;

    public Plane(String manufacturer, String name, String type, int yearOfManufacture, String countryOfOrigin, String description, String imageUrl) {
        this.manufacturer = manufacturer;
        this.name = name;
        this.type = type;
        this.yearOfManufacture = yearOfManufacture;
        this.countryOfOrigin = countryOfOrigin;
        this.description = description;
        this.imageUrl = imageUrl;
    }
    // Constructors, getters, and setters can be generated by Lombok
}
