package org.example.planemuseumbackend.Entities;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.lang.NonNull;

import java.lang.annotation.Target;

@Entity
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "users",
        uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Users {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    int id;
    String name;
    @Column(unique = true, nullable = false)
    String email;
    String password;
    Boolean isAdmin;

    public Users(String name, String email, String password, Boolean isAdmin) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.isAdmin = isAdmin;
    }
    // Constructors, getters, and setters can be generated by Lombok
}
